[data]
data_root_path = "/gpfs/projects/uab103/uab020077/data/processed_data/tba"
dataset_id = "2025-07-04_04_ESPM154_vol_000"
batch_size = 8
val_split = 0.1
shuffle_train = true
num_workers = 16
pin_memory = true
drop_last = false
architecture = "custom"

[built_in_model]
latent_dim = 256
hidden_dim = 512
num_layers = 16
num_heads = 32
dropout = 0.1

[custom_model]
target = "v1tovideo.neural_autoencoder.models:TAE_v1_1"
input_dim = 32
latent_dim = 32
latent_num_tokens = 5443

[train]
epochs = 20
learning_rate = 0.0001
weight_decay = 0.0001
grad_clip_norm = 1.0
device = "cuda:0"

[train.loss]
name = "combined"
weight_id = 1.0
weight_time = 1.0
weight_rec = 1.0
name_id = "cross_entropy"
name_time = "masked_mse"
name_rec = "masked_mse"
poisson_log_input = true
poisson_full = false
poisson_eps = 1e-08

[output]
dir = "/gpfs/projects/uab103/uab020077/transformer_arch/transformer_arch_4/transformer_arch/outputs/neural_autoencoder/run_20"
